# -*- coding: utf-8 -*-
"""AI CHATBOT FOR COLLEGE ERP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lw7EVEnuN2AvMmyAArqI64o0EtQ0_HU7
"""

!pip install streamlit pandas pyngrok openai

# ==============================
# Gen-AI Student Management Chatbot
# Attendance | Marks | Exam Dates
# Streamlit App (Final Year Project Example)
# ==============================

# Install required libraries (Run in Colab if needed)
# !pip install streamlit pandas pyngrok openai

import streamlit as st
import pandas as pd

# ------------------------------
# Sample Student Database
# ------------------------------
data = {
    "Student_ID": ["101","102","103"],
    "Name": ["Rahul","Anita","Kiran"],
    "Attendance": ["92%","85%","78%"],
    "Marks": ["88","91","76"],
    "Exam_Date": ["10-Apr-2026","10-Apr-2026","10-Apr-2026"]
}

df = pd.DataFrame(data)

# ------------------------------
# Streamlit UI
# ------------------------------
st.title("🎓 Student Management System Chatbot")

st.write("### Ask Questions About:")
st.write("✔ Attendance queries")
st.write("✔ Marks queries")
st.write("✔ Exam dates")

query = st.text_input("Enter your question")

# ------------------------------
# Chatbot Logic
# ------------------------------
def chatbot(query):

    query = query.lower()

    # Attendance
    if "attendance" in query:
        sid = ''.join(filter(str.isdigit, query))
        student = df[df["Student_ID"] == sid]

        if not student.empty:
            return f"Attendance of Student {sid} is {student.iloc[0]['Attendance']}"
        else:
            return "Student ID not found"

    # Marks
    elif "marks" in query:
        sid = ''.join(filter(str.isdigit, query))
        student = df[df["Student_ID"] == sid]

        if not student.empty:
            return f"Marks of Student {sid} is {student.iloc[0]['Marks']}"
        else:
            return "Student ID not found"

    # Exam Date
    elif "exam" in query or "date" in query:
        return f"Next Exam Date is {df.iloc[0]['Exam_Date']}"

    else:
        return "Please ask about attendance, marks, or exam dates."

# ------------------------------
# Display Response
# ------------------------------
if query:
    response = chatbot(query)
    st.success(response)